### ISSUE TITLE
Error when going to Paypal from order form

### ISSUE THREAD

**Issue by realitycheque** [mikeprosser/project-nisei#1]
/var
/www
/html
/project-nisei
/app
/Http
/Controllers
/Web
/PaypalController.php

    use PayPal\Api\Payer;
    use PayPal\Api\Payment;
    use PayPal\Api\RedirectUrls;
    use PayPal\Api\ExecutePayment;
    use PayPal\Api\PaymentExecution;
    use PayPal\Api\Transaction;
     
    class PaypalController extends Controller
    {
        private $_api_context;
        /**
         * Create a new controller instance.
         *
         * @return void
         */
        public function __construct()
        {        
            /** setup PayPal api context **/
            $paypal_conf = \Config::get('paypal');
            $this->_api_context = new ApiContext(new OAuthTokenCredential($paypal_conf['client_id'], $paypal_conf['secret']));
            $this->_api_context->setConfig($paypal_conf['settings']);
        }
     
        /**
         * Retrieve correct price for kit from db
         *
         */
        private function getCorrectPrice($kit_slug) {
     
            $event = DB::table('events')
                ->where('slug', $kit_slug)
                ->select('price')
                ->first();
     
            if ($event) {
                return floatval($event->price);
            }
     
            return null;
        }

Arguments

    "Class 'PayPal\Rest\ApiContext' not found"

**Comment by mikeprosser** [comment]
The missing package has been installed and this appears to be working now
