### ISSUE TITLE
Request: new redirect

### ISSUE THREAD

**Issue by vesperius** [mikeprosser/project-nisei#106]
FROM: nisei.net/find-people
TO: nisei.net/op/around-the-world

RELATED TO: https://github.com/mikeprosser/project-nisei/pull/105

**Comment by vesperius** [comment]
Should be resolved with https://github.com/mikeprosser/project-nisei/commit/8dd69eb49b907fb93bfe1857770bbc5dbf9e21f4

Thank you @Absotively and @x3N1GM4x :)

**Comment by x3N1GM4x** [comment]
Resolved by #105.
