### ISSUE TITLE
Error editing article with featured image

### ISSUE THREAD

**Issue by realitycheque** [mikeprosser/project-nisei#3]
/var
/www
/html
/project-nisei
/app
/Http
/Controllers
/Admin
/BlogsController.php

         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function update(UpdateBlogsRequest $request, $id)
        {
            if (! Gate::allows('blog_edit')) {
                return abort(401);
            }
     
            $blog = Blog::findOrFail($id);
            $requestData = $request->all();
     
            if ($request->listing_image) {
                $request->file('listing_image')->move(
                    base_path() . '/public/listing_images/', $request->listing_image->getClientOriginalName()
                );
     
                $requestData['listing_image'] = '/listing_images/' . $request->listing_image->getClientOriginalName();
            } else {
                $requestData['listing_image'] = $blog->$listing_image;
            }
     
            $blog->update($requestData);
     
            return redirect()->route('admin.blogs.index');
        }
     
     
        /**
         * Display Blog.
         *
         * @param  int  $id
         * @return \Illuminate\Http\Response
         */
        public function show($id)
        {
            if (! Gate::allows('blog_view')) {
                return abort(401);
            }
            $blog = Blog::findOrFail($id);

Arguments

    "Undefined variable: listing_image"

**Comment by realitycheque** [comment]
If you reselect the image, it's all fine.

**Comment by mikeprosser** [comment]
This should now behave as expected, when editing an article that already has a set listing image it will preserve that image unless a new one is specifically set
