### ISSUE TITLE
Please add a URL to the "Supported Formats" page

### ISSUE THREAD

**Issue by vesperius** [mikeprosser/project-nisei#61]
http://nisei.net/op/supported-formats could benefit from adding http://nisei.net/article/SC2019 as the hyperlink for "A single copy of System Core 2019 is the only legal product" (found at the bottom of the page).

Thanks! :-)

![Screenshot_2019-03-18 NISEI - Supported Formats](https://user-images.githubusercontent.com/16701215/54529637-b900f500-4980-11e9-989c-2cd72011ba9d.png)

**Comment by x3N1GM4x** [comment]
Thanks for the suggestion @vesperius - would just linking the "System Core 2019" text within the highlighted sentence be ok with you? Seems it would be a rather long link text otherwise...

**Comment by vesperius** [comment]
Yes, that would work as well :) Thanks!
